remote_theme: tuur29/pages-themes-cayman
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: false
darkmode: false
hide_first_title: true
color:
  header: "#fff"
  gradient_left: "#c28ddd"
  gradient_right: "#7a70ba"
  link: "#5d6ba8" # this default to gradient_color
  section_title: "#2b8da7" # this default to gradient_color

