remote_theme: tuur29/pages-themes-cayman
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: false
darkmode: false
hide_first_title: true
color:
  header: "#fff"
  gradient_left: "#2b8da7"
  gradient_right: "#baadf1"
  section_title: "#2b8da7" # this default to gradient_color
  link: "#7a70ba" # this default to gradient_color
  

