theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: true
darkmode: false
logo_url: ./icons/user.ico # Either absolute or relative url
