remote_theme: pages-themes/cayman@v0.2.0
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: false
darkmode: false
hide_first_title: true
color:
  header: "#fff"
  gradient_left: "#2f99b6"
  gradient_right: "#7857db"
  section_title: "#2b8da7" # this default to gradient_color
  link: "#7857db" # this default to gradient_color
  

