remote_theme: tuur29/pages-themes-cayman
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: true
darkmode: false
hide_first_title: true
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
