remote_theme: tuur29/pages-themes-cayman
title: Yong-chan Park
description: M.S./Ph.D. Student at Seoul National University

show_downloads: false
darkmode: false
hide_first_title: true
color:
  header: "#fff"
  gradient_left: "#155799"
  gradient_right: "#c28ddd"
  section_title: "#2b8da7" # this default to gradient_color
  link: "#7857db" # this default to gradient_color
  

